"""API contracts (Pydantic). Everything that crosses the HTTP boundary is defined here."""

import unicodedata
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from app.core.types import RouteKind

CLIENT_ID_PATTERN = r"^C-\d{1,6}$"

# rule = deterministic business rule, llm = generated by a model,
# extractive = passages quoted verbatim (no LLM configured or LLM unavailable),
# deterministic = scripted agent plan without LLM, none = no answer (escalation).
AnswerMode = Literal["rule", "llm", "extractive", "deterministic", "none"]
RetrievalMode = Literal["hybrid", "bm25", "none"]
ActionStatus = Literal["pending", "approved", "rejected"]


class AskRequest(BaseModel):
    q: str = Field(min_length=3, max_length=2000, description="Demande du client (texte libre)")
    client_id: str | None = Field(default=None, pattern=CLIENT_ID_PATTERN, examples=["C-12"])
    montant: float | None = Field(default=None, gt=0, le=1_000_000, description="Montant en €")

    @field_validator("q", mode="before")
    @classmethod
    def _canonical_text(cls, value: object) -> object:
        """One form of the text for triage, masking and search.

        Accents are composed (a decomposed "é" would not match the vocabulary of the
        rules) and invisible format or control characters are removed, line breaks and
        tabs excepted. Runs before the length check, which then applies to real text.
        """
        if not isinstance(value, str):
            return value  # left to the type validation
        composed = unicodedata.normalize("NFC", value)
        visible = "".join(
            ch for ch in composed if ch in "\n\t" or unicodedata.category(ch) not in ("Cf", "Cc")
        )
        return visible.strip()

    @field_validator("client_id", mode="before")
    @classmethod
    def _normalise_client(cls, value: object) -> object:
        if not isinstance(value, str):
            return value  # None, or a wrong type left to the type validation
        return value.strip().upper() or None


class Citation(BaseModel):
    ref: int  # number used in the answer: "[1]"
    doc: str
    title: str
    page: int
    section: str = ""
    chunk_id: str
    excerpt: str
    score: float


class Usage(BaseModel):
    model: str | None = None
    llm_calls: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost_eur: float = 0.0  # computed from real token usage; 0.0 when no LLM was called


class ProposedAction(BaseModel):
    action_id: str
    type: Literal["create_ticket"] = "create_ticket"
    status: ActionStatus = "pending"
    payload: dict
    ticket_id: str | None = None


class AskResponse(BaseModel):
    request_id: str
    route: RouteKind
    mode: AnswerMode
    answer: str
    citations: list[Citation] = Field(default_factory=list)
    confidence: float | None = None
    needs_validation: bool = True
    proposed_action: ProposedAction | None = None
    ticket_id: str | None = None  # ticket created by the RG-03 automation
    decision_log: list[str] = Field(default_factory=list)
    pii_redacted: list[str] = Field(default_factory=list)  # PII types masked in the request
    usage: Usage = Field(default_factory=Usage)
    latency_ms: int = 0
    retrieval_mode: RetrievalMode = "none"


class Ticket(BaseModel):
    ticket_id: str
    client_id: str | None
    subject: str
    body: str
    kind: Literal["litige_standard", "intervention"]
    priority: str | None = None
    source: Literal["automation", "agent"]
    status: str = "open"
    created_at: datetime
    created_by: str
    request_id: str | None = None


class ActionDecision(BaseModel):
    validator: str = Field(min_length=1, max_length=80, description="Who approves or rejects")
    reason: str = Field(default="", max_length=500)
    # On approval only: the priority the validator sets in place of the proposed one.
    priority: Literal["P1", "P2", "P3"] | None = None


class ActionResult(BaseModel):
    action: ProposedAction
    ticket: Ticket | None = None


class FeedbackRequest(BaseModel):
    request_id: str = Field(min_length=1, max_length=64)
    ok: bool
    comment: str = Field(default="", max_length=2000)


class FeedbackSaved(BaseModel):
    saved: bool = True
    request_id: str
    route: RouteKind | None = None


class FeedbackStats(BaseModel):
    n: int
    ok_rate: float | None
    by_route: dict[str, dict[str, int]]


class IngestResponse(BaseModel):
    docs: int
    chunks: int
    retrieval_mode: RetrievalMode
    embedding_backend: str | None = None
    embedding_model: str | None = None
    vector_store: str | None = None  # "numpy" | "qdrant" | None
    duration_ms: int
    warnings: list[str] = Field(default_factory=list)


class MetricsResponse(BaseModel):
    requests: int
    by_route: dict[str, int]
    by_mode: dict[str, int]
    latency_ms_p50: int | None
    latency_ms_p95: int | None
    cost_eur_total: float
    cost_eur_avg: float | None
    llm_call_share: float | None  # share of requests that called an LLM
    escalation_rate: float | None  # share of requests routed to a human
    errors: int
    feedback: FeedbackStats
    pending_actions: int


class ReadyResponse(BaseModel):
    ready: bool
    checks: dict[str, str]
